paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
gems: [jekyll-paginate]


exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown

title: Shunmian
description: Stylish Jekyll Theme
disqus: shunmianjohnson # add disqus short name here
author:
  name: Shunmian
  email: shunmian@gmail.com
  github: shunmian
  bio: 技术分享博客，记录搬砖的点滴！
  email_md5: 02eefecba7f0b21939d12a37f94bf5df

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

baseurl: http://www.shunmian.me
